# _config.yml
title: Cub Scouts Pack 152 - Berlin, Germany
description: Official website for Cub Scouts Pack 152 - Berlin, Germany
url: "https://pack152berlin.github.io"
baseurl: ""

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages settings
github:
  is_project_page: true

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - README.md
  - LICENSE.md

# Build settings
markdown: kramdown
permalink: pretty

# (Recommended) Set your timezone
timezone: Europe/Berlin
email: pack152berlin@gmail.com